# Generated by Django 4.1.13 on 2025-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurationId', models.CharField(max_length=100, unique=True)),
                ('array', models.JSONField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
